module.exports = {
  apps: [
    {
      name: 'mailsuite-api',
      script: 'server.js',
      cwd: './MailSuite',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        PORT: 5050,
      },
      error_file: './logs/mailsuite-api-error.log',
      out_file: './logs/mailsuite-api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'mailsuite-frontend',
      script: 'node_modules/.bin/next',
      args: 'start -p 3000',
      cwd: './MailSuite/frontend',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      error_file: './logs/mailsuite-frontend-error.log',
      out_file: './logs/mailsuite-frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'pipepass',
      script: 'server.py',
      interpreter: 'python3',
      cwd: './PipePass',
      instances: 1,
      autorestart: true,
      watch: false,
      env: {
        PORT: 7070,
        MAILSUITE_URL: 'http://localhost:5050',
        SELF_URL: 'http://localhost:7070',
      },
      error_file: './logs/pipepass-error.log',
      out_file: './logs/pipepass-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
  ],
};
